.travis.yml, Dockerfile, e2e/protractor.conf.js, karma.conf.js
Adicionado Integração Contínua do GitHub.
Fix #8
**Checklist**
=> [AMB07] Configurado Integração Continua

package-lock.json, package.json, server.js
Deploy contínuo dos ambientes do frontend feito no Heroku.
[Desenvolvimento](https://amika-dev.herokuapp.com)
[Homologação](https://amika-stg.herokuapp.com)
[Produção](https://amika-prod.herokuapp.com)
Fixes #6 
Fixes #7
**Checklist**
=> Deploy dos Ambientes de PRs, Desenvolvimento, Homologação e Produção do Frontend

CODE_OF_CONDUCT.md
Adicionando código de Conduta do projeto para este repositório
Código de conduta conforme o apresentado na Wiki oficial.
**Checklist**
=> Criando código de conduta

LICENSE
Adicionando licença deste repositório e acordo com a licença do projeto
Licença escolhida em acordo com a equipe e já presente na Wiki foi a MIT
**Checklist**
=> Criando licença do projeto

CONTRIBUTING.md
Adicionando o guia de contribuição do projeto de acordo com a wiki oficial.
Guia de contribuição feito seguindo o arquivo na Wiki do projeto.
**Checklist**
=> Criando guia de contribuição

src/app/login/login.component.ts, src/environments/environment.prod.ts
Adicionei a variável da url de produção.
**Checklist**
=> HOT-FIX Deployment do Frontend de Desenvolvimento

.github/ISSUE_TEMPLATE/requisitar-funcionalidade.md
Refatoração do template usado para issues de requisitar funcionalidade no frontend. Na refatoração foram adicionados os critérios de aceitação e telas que devem ser criadas com alguns requisitos de usabilidade do usuário.
FIX #46 
**Checklist**
=> issue46 refatorar o template de requisitar funcionalidade.

src/app/agendas/agenda.service.ts, src/app/login/login.component.css, src/app/turmas/turma-edit/turma-edit.component.html, src/app/turmas/turma.service.ts, src/app/turmas/turmas.component.html, src/app/turmas/turmas.component.ts, src/app/turmas/turmas.model.ts
Adequando refatorações do back no frontend
FIX #38 
**Checklist**
=> [Issue38] Adequando refatoracoes

Dockerfile, docker-compose.yml
FIX #59 
Troca imagem base para Alpine
**Checklist**
=> Corrige Dockerfile

.github/ISSUE_TEMPLATE/requisitar-refatoramento.md
Foi criado o template para as issues de refatoramento 
FIX #45 
**Checklist**
=> Criando o template das issues de refatoramento

src/app/perfil-usuario/perfil-usuario.component.ts, src/app/perfil-usuario/perfil-usuario.model.ts
=> [ISSUE - 64] Refatorando perfil do aluno

src/app/humor/humor.component.ts, src/app/humor/humor.model.ts
Resolvendo bug do tipo do atributo data no humor
Resolvendo erro durante o docker-compose, adicionando data durante a criação de um novo humor
FIX #69
**Checklist**
=> Resolvendo bug do tipo do atributo data no humor

src/app/app.component.ts
Alteração do autenticação para público
FIX #78 
**Checklist**
=> [Hotfix] Consertando bug do ng build

src/app/app.component.css, src/app/app.component.html, src/app/app.component.ts
Adicionando menu de navegação inferior para celular
FIX #72 
**Checklist**
=> Issue 72 bottom menu

src/app/app.component.css, src/app/app.component.ts, src/app/app.module.ts, src/app/turmas/turma-edit/turma-edit.component.css, src/app/turmas/turma-edit/turma-edit.component.html, src/app/turmas/turmas-create-dialogo.css, src/app/turmas/turmas-create-dialogo.html, src/app/turmas/turmas.component.css, src/app/turmas/turmas.component.html, src/app/turmas/turmas.component.ts, src/styles.css
Refatoração da tela de turmas, tanto para desktop quanto para mobile.
FIX #76 
Desktop
Mobile
**Checklist**
=> Issue 76 refatorar tela turma

src/app/autenticacao.service.ts
Adicionei o JWT no valor da autenticação com o token.
FIX #88 
**Checklist**
=> [HOT-FIX] Adiciona JWT no header de autorização

src/app/perfil-usuario/perfil-usuario.service.ts
Corrigido a URN de requisição para perfil de aluno.
FIX #90 
**Checklist**
=> [HOT-FIX] Corrige URN do perfil de aluno

angular.json, package.json, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.stg.ts
Adicionei as urls respectivos de cada deployment.
FIX #96
**Checklist**
=> [HOT-FIX] Corrige sincronização de deployments

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/page-not-found/page-not-found.component.css, src/app/page-not-found/page-not-found.component.html, src/app/page-not-found/page-not-found.component.spec.ts, src/app/page-not-found/page-not-found.component.ts
Adicionada página para o erro 404 - página não encontrada.
Se um usuário, por acaso, entrar em um link que não existe (ex.: http://localhost:4200/naoExiste), este link o redirecionará para a página de erro 404 - página não encontrada. Ainda na página 404, há um link para redirecionar o usuário para a página inicial.
FIX #68 
**Screenshots**
**Checklist**
=> Criação da página do erro 404 - página não encontrada.

src/styles.css
Correção do bug no _styles.css_. (Adição de um ; (ponto e vírgula) faltante)
FIX #95 
**Checklist**
=> Conserto do WARNING no styles.css

src/app/humor/humor.component.css, src/app/humor/humor.component.html, src/app/humor/humor.service.ts
Refatoração da tela de humor, tanto para desktop quanto para mobile.
FIX #77 
Obs: Está dando um erro de imagem, que já deu outra vez no github. Tentarei colocar novamente depois.
Foram feitas poucas alterações por conta do componente já estar bem feito e a página não ter muitas funcionalidades.
**Checklist**
=> Issue 77 Refatorar humor

src/app/area-informativa/area-informativa.component.css, src/app/area-informativa/area-informativa.component.html, src/app/area-informativa/area-informativa.component.ts
Mudei a forma de como era feito a disponibilização dos atendentes.
FIX #94 
**Checklist**
=> Refatora área informativa

src/app/login/login.component.css, src/app/login/login.component.html, src/app/login/login.component.ts, src/app/requisicao.service.ts
Tela de cadastro foi refatorada, e adicionada na página de login.
FIX #98 
**Checklist**
=> Issue 98 refatora tela cadastro

src/app/app.component.html
Renomeação dos títulos da navbar
FIX #112
**Checklist**
=> Renomeando titulos das paginas

src/app/humor/humor.component.ts, src/app/humor/humor.service.ts
Criação do método que recebe o status do humor do aluno no dia atual.
FIX #114 
**Checklist**
=> Tratando retorno de status do humor do dia

src/app/app.component.css, src/app/app.component.html, src/app/app.component.ts, src/app/perfil.service.ts
Agora, o aluno pode mudar sua foto de perfil.
FIX #83 
Foto padrão:
Foto editada:
**Checklist**
=> Adiciona troca de foto de perfil de aluno

src/app/grupos/grupo-edit/grupo-edit.component.css, src/app/grupos/grupo-edit/grupo-edit.component.html, src/app/grupos/grupos.component.css, src/app/grupos/grupos.component.html, src/app/lista-de-matricula/lista-de-matricula.component.css, src/app/lista-de-matricula/lista-de-matricula.component.html, src/app/login/login.component.css, src/app/login/login.component.html, src/app/turmas/turma-edit/turma-edit.component.css, src/app/turmas/turma-edit/turma-edit.component.html, src/app/turmas/turmas-create-dialogo.css, src/app/turmas/turmas.component.css, src/app/turmas/turmas.component.html
Padronizando componentes da aplicação com o Angular Material
FIX #118 
Foram utilizados os inputs e seus recursos nos componentes de :
- Turmas
- Grupos
- Login
- Registro
**Checklist**
=> Issue 118 Ajustando Angular Material

.travis.yml, README.md, package-lock.json, package.json
Corrige badges de testes para mostrar a cobertura de códigos testados.
FIX #130 
**Checklist**
=> [HOT-FIX] Issue 130 Badges Testes

src/app/app.component.css, src/app/app.component.html
Feitas as alterações de links e ícones da sidebar e bottombar do administrador.
FIX #123 
**Checklist**
=> Alteração dos links e ícones da sidebar e bottom bar do administrador

src/app/agendas/agendas.component.css, src/app/agendas/agendas.component.html, src/app/grupos/grupos.component.css, src/app/turmas/turmas.component.css
Nas páginas de grupo, turmas e agendas, foi adicionado uma maior margem na versão mobile para que o menu de navegação inferior não sobreponha o botão
FIX #129 
**Checklist**
=> Ajustando posicao do botao de adicionar no mobile

src/app/app.component.css, src/app/app.component.html
Adicionado o link para a página inicial na logo do Amika, tanto no texto quanto na imagem, no canto direito da tela.
FIX #126 
**Checklist**
=> Adicionado o link para a página inicial na logo do Amika.

src/app/agendas/agenda-edit/agenda-edit.component.html, src/app/agendas/agenda-edit/agenda-edit.component.ts, src/app/agendas/agenda.service.ts, src/app/agendas/agendas-create-dialogo.html, src/app/agendas/agendas.component.html, src/app/agendas/agendas.component.ts, src/app/grafico-humor/grafico-humor.component.ts, src/app/grupos/grupo-edit/grupo-edit.component.html, src/app/grupos/grupos.component.html, src/app/lista-de-matricula/lista-de-matricula.component.html, src/app/lista-de-matricula/lista-de-matricula.component.ts, src/app/login/login.component.html, src/app/turmas/turma-edit/turma-edit.component.html, src/app/turmas/turmas.component.html
Corrigindo bugs do heroku
FIX #145 
**Checklist**
=> Issue 145 Corrigindo bugs do Heroku

src/app/grupos/grupos.component.css, src/app/grupos/grupos.component.html, src/app/grupos/grupos.component.ts
Adicionadas as fotos dos alunos na aba de grupos do professor.
FIX #127 
**Checklist**
=> Adicionadas as fotos dos alunos na aba de grupos do professor.

src/app/materiais/materiais.component.css, src/app/materiais/materiais.component.html
Adição da margem superior na tela desktop de materiais e diminuição de margens de título da versão mobile.
FIX #154 
**Checklist**
=> Issue 154 - Margem superior da tela de materiais

src/app/app.component.html, src/app/humor/humor.component.html, src/app/humor/humor.component.ts
O usuário agora não consegue selecionar outros níveis de humor depois de já ter salvo o humor naquele dia.
FIX #157 
**Checklist**
=> Desabilitando seleção de humor já adicionado

src/app/app.component.html
Removendo abertura da sidebar ao clicar no ícone
FIX #153 
**Checklist**
=> [HOTFIX] Removendo abertura da sidebar ao clicar na logo

src/app/agendas/agendas.component.css
Consertando bug de agendas
FIX #152 
**Checklist**
=> [HOTFIX] Consertando bug de agendas

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/grupo/grupo.component.css, src/app/grupo/grupo.component.html, src/app/visualizar-materiais/visualizar-materiais.component.css, src/app/visualizar-materiais/visualizar-materiais.component.html, src/app/visualizar-materiais/visualizar-materiais.component.spec.ts, src/app/visualizar-materiais/visualizar-materiais.component.ts
Adicionando tela de visualizar materiais
FIX #158 
Por conta do curto tempo para finalizar está tela, não foi possível caprichar muito.
**Checklist**
=> Issue 158 Adicionando tela de visualizar materiais

src/app/humor/humor.component.html
Corrigindo bug na chamada de um método inexistente
FIX #163 
**Checklist**
=> [HOTFIX] Corrigindo bug na chamada de um método inexistente

src/app/grupo/grupo.component.html
Padronizando tamanho das imagens em grupo
FIX #166 
**Checklist**
=> [HOTFIX] Padronizando tamanho das imagens em grupo

src/app/requisicao.service.ts
Adicionando mensagens de validação quando o usuário tenta cadastrar.
FIX #171 
**Checklist**
=> Adicionando mensagem de validacao ao registrar

src/app/agendas-realizadas/agendas-realizadas.component.ts
Erro no heroku na issue de realizar agenda
**Checklist**
=> [HOTFIX] Consertando erro heroku

src/app/app-routing.module.ts
Corrigindo erro do heroku no app-routing.module.ts
**Checklist**
=> [HOTFIX] Corrigindo erro do heroku

src/app/app.component.html
O botão de agenda da navbar do aluno agora está linkado com a página corretas.
FIX #176 
**Checklist**
=> Alterando rota do botao de agendas da navbar do aluno
